name: 'NautScanner Security Scan'
description: 'Scan your dependencies for security vulnerabilities'
author: 'NautScanner Team'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  api_key:
    description: 'NautScanner API key (optional for open source version)'
    required: false
  api_url:
    description: 'NautScanner API URL'
    required: false
    default: 'https://api.nautscanner.io/v1'
  fail_on_critical:
    description: 'Fail the build if critical vulnerabilities are found'
    required: false
    default: 'false'
  min_severity:
    description: 'Minimum severity to report (low, medium, high, critical)'
    required: false
    default: 'medium'

outputs:
  vulnerabilities_found:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.scan.outputs.vulnerabilities_found }}
  scan_result:
    description: 'Scan result (pass or fail)'
    value: ${{ steps.scan.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: Detect ecosystems
      id: detect
      shell: bash
      run: |
        echo "Detecting package managers..."
        ECOSYSTEMS=""

        if [ -f "package.json" ]; then
          echo "Found package.json (npm)"
          ECOSYSTEMS="$ECOSYSTEMS npm"
        fi

        if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
          echo "Found Python dependencies"
          ECOSYSTEMS="$ECOSYSTEMS python"
        fi

        if [ -f "go.mod" ]; then
          echo "Found go.mod"
          ECOSYSTEMS="$ECOSYSTEMS go"
        fi

        echo "ecosystems=$ECOSYSTEMS" >> $GITHUB_OUTPUT

    - name: Extract dependencies (npm)
      if: contains(steps.detect.outputs.ecosystems, 'npm')
      shell: bash
      run: |
        if [ -f "package.json" ]; then
          node -e "
            const pkg = require('./package.json');
            const deps = {
              ...pkg.dependencies || {},
              ...pkg.devDependencies || {}
            };
            const formatted = Object.entries(deps).map(([name, version]) => ({
              name,
              version: version.replace(/^[\^~]/, ''),
              type: pkg.dependencies?.[name] ? 'direct' : 'dev'
            }));
            console.log(JSON.stringify(formatted, null, 2));
          " > dependencies-npm.json
        fi

    - name: Extract dependencies (Python)
      if: contains(steps.detect.outputs.ecosystems, 'python')
      shell: bash
      run: |
        if [ -f "requirements.txt" ]; then
          python3 -c "
import re
import json
deps = []
with open('requirements.txt') as f:
    for line in f:
        line = line.strip()
        if line and not line.startswith('#'):
            match = re.match(r'^([a-zA-Z0-9\-_]+)==([0-9\.]+)', line)
            if match:
                deps.append({
                    'name': match.group(1),
                    'version': match.group(2),
                    'type': 'direct'
                })
print(json.dumps(deps, indent=2))
          " > dependencies-python.json
        fi

    - name: Extract dependencies (Go)
      if: contains(steps.detect.outputs.ecosystems, 'go')
      shell: bash
      run: |
        if [ -f "go.mod" ]; then
          go list -m -json all | jq -s 'map(select(.Main != true) | {name: .Path, version: .Version, type: "direct"})' > dependencies-go.json
        fi

    - name: Submit scan to NautScanner
      id: scan
      shell: bash
      env:
        API_KEY: ${{ inputs.api_key }}
        API_URL: ${{ inputs.api_url }}
        REPO_ID: ${{ github.repository }}
      run: |
        # Combine all dependencies
        DEPENDENCIES="[]"

        if [ -f "dependencies-npm.json" ]; then
          DEPENDENCIES=$(cat dependencies-npm.json)
        elif [ -f "dependencies-python.json" ]; then
          DEPENDENCIES=$(cat dependencies-python.json)
        elif [ -f "dependencies-go.json" ]; then
          DEPENDENCIES=$(cat dependencies-go.json)
        fi

        # Create scan request
        SCAN_REQUEST=$(jq -n \
          --arg repo_id "$REPO_ID" \
          --argjson deps "$DEPENDENCIES" \
          --arg ecosystem "${{ steps.detect.outputs.ecosystems }}" \
          --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          '{
            repo_id: $repo_id,
            dependencies: $deps,
            ecosystem: $ecosystem,
            timestamp: $timestamp
          }')

        # Submit to API
        RESPONSE=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $API_KEY" \
          -d "$SCAN_REQUEST" \
          "$API_URL/scan")

        echo "$RESPONSE" | jq .

        VULN_COUNT=$(echo "$RESPONSE" | jq -r '.vulnerabilities_found // 0')
        echo "vulnerabilities_found=$VULN_COUNT" >> $GITHUB_OUTPUT

        # Check for critical vulnerabilities
        CRITICAL_COUNT=$(echo "$RESPONSE" | jq '[.vulnerabilities[] | select(.severity == "critical")] | length')

        if [ "${{ inputs.fail_on_critical }}" = "true" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "result=fail" >> $GITHUB_OUTPUT
          echo "::error::Found $CRITICAL_COUNT critical vulnerabilities"
          exit 1
        else
          echo "result=pass" >> $GITHUB_OUTPUT
        fi

    - name: Generate summary
      shell: bash
      run: |
        echo "## NautScanner Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Vulnerabilities Found:** ${{ steps.scan.outputs.vulnerabilities_found }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Scan Result:** ${{ steps.scan.outputs.result }}" >> $GITHUB_STEP_SUMMARY
